name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          
      - name: Install Carthage
        run: brew install carthage
      
      - name: Clean derived data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Build dependencies
        run: carthage bootstrap --use-xcframeworks --platform iOS,macOS --cache-builds

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.3.1.app

      - name: Build and Test (iOS)
        run: xcodebuild test -project Source/ImageResourceCore.xcworkspace -scheme "ImageResourceCore" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4" ONLY_ACTIVE_ARCH=YES SWIFT_TREAT_WARNINGS_AS_ERRORS=YES OTHER_SWIFT_FLAGS="-D ED_SKIP_SWIFT_FORMAT"

      - name: Build and Test (macOS)
        run: xcodebuild test -project Source/ImageResourceCore.xcworkspace -scheme "ImageResourceCore" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx ONLY_ACTIVE_ARCH=YES SWIFT_TREAT_WARNINGS_AS_ERRORS=YES OTHER_SWIFT_FLAGS="-D ED_SKIP_SWIFT_FORMAT"
